name: Code review
on: [pull_request]
jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: fxchen/code-review@latest
        with:
          model: 'gpt-3.5-turbo-16k'
          openai-key: ${{ secrets.OPENAI_API_KEY }}
          # prompt: |  # Commenting out the invalid input
          #   Please review the code and provide suggestions for improvement.
          #   - Check for any logical errors or inconsistencies.
          #   - Suggest optimizations or refactorings.
          #   - Ensure best practices are followed (e.g., proper use of hooks, state management).
          #   - Check for any potential security vulnerabilities.
          #   - Provide general feedback on code readability and maintainability.

