name: Testing

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --reporter mocha-allure-reporter

      - name: Generate Allure report
        run: allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v3  # Cập nhật phiên bản ở đây
        with:
          name: allure-report
          path: ./allure-report